---
- name: 1. Check if ntp is already installed.
  yum:
    name: ['ntp']
    state: present
    enablerepo: epel
  tags: ntp

- name: 2. Check if ntpd is already running and enabled.
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp
