---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - { role: base_packages }
    - { role: timezone }
    - { role: locale }
    - { role: epel }
    - { role: ntp }

- hosts: webservers
  become: yes
  gather_facts: no
  roles:
    - { role: pip }
    - { role: vcs }

- hosts: dbservers
  become: yes
  gather_facts: no
  roles:
    - { role: mysql }
